### ISSUE TITLE
Add BelongsToSearch in Nested form

### ISSUE THREAD

**Issue by bilal14079** [nickcharlton/administrate-field-nested_has_many#22] opened 2019-04-09 11:34 UTC
Hello guys! I hope everybody is doing great.
I'm facing problem to add belongs_to search from "administrate-field-belongs_to_search" in dropdown of nested forms.
As you can see in attachment, order_items is nested form for new order and I need to add search on its product dropdown.
Waiting for your help.

![image](https://user-images.githubusercontent.com/42926211/55797203-439ec500-5ae5-11e9-9044-94b73857a759.png)

**Comment by nickcharlton** [comment] 2020-02-07 12:45
👋, I'm not sure I understand. Do you want to add a search box _inside_ nested field area?

**Comment by nunesmatheus** [comment] 2020-07-14 14:00
@nickcharlton, [administrate-field-belongs_to_search](https://github.com/fishbrain/administrate-field-belongs_to_search) allows us to search through records to set a belongs_to relationship. The problem is, when we combine it with **administrate-field-nested_has_many**, it breaks and the records for the belongs_to relationship cannot be searched. This happens because **administrate-field-belongs_to_search** runs a [javascript code](https://github.com/fishbrain/administrate-field-belongs_to_search/blob/master/app/assets/javascripts/belongs_to_search.js) when the form is rendered to add the search feature, but it is not run when we add a nested object with **administrate-field-nested_has_many**, like when clicking on "Add Order Item" on the screenshot @bilal14079 posted.

The solution I found was to run the JS code to add the search feature on the JS event of adding the nested object. I just added this code to my `app/views/admin/application/_javascript.html.erb`:
``` html
<script>
  $(document).on('click', '.field-unit--nested-has-many .add_fields', () => {
    $(".field-unit--belongs-to-search select").each(function initializeSelectize(index, element) {
      var $element = $(element);
      $element.selectize({
        valueField: 'id',
        labelField: 'dashboard_display_name',
        searchField: 'dashboard_display_name',
        create: false,
        searchUrl: $element.data('url') + '?search=',

        load: function(query, callback) {
          if (!query.length) return callback();
          var searchUrl = this.settings.searchUrl;
          $.ajax({
            url: searchUrl + encodeURIComponent(query),
            type: 'GET',
            error: function() {
              callback();
            },
            success: function(res) {
              callback(res.resources);
            }
          });
        },
      });
    });
  });
</script>
```

I am sure there is a more clever solution for this, but at least it works and will, hopefully, be helpful for someone that faces this problem and ends up here.

**Comment by nickcharlton** [comment] 2020-07-23 16:35
Ah I see! This is a fun problem you get with otherwise unconnected plugins and I'm not sure who should provide this JS. If `belongs_to_search` had a way to for `nested_has_many` to hook into, I'd be open to adding something to it.

Otherwise it seems like the solution of documenting it here if someone else has the same combination of plugins is alright.

I'm going to close this as you've got a solution to your problem and anything else is probably quite a bit of work. But feel free to re-open if you've got another potential solution.

**Closed by nickcharlton** 2020-07-23 16:35 UTC
